services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    
  basketdb:
    container_name: basketdb
    image: postgres
    
  distributedcache:
    container_name: distributedcache
    image: redis
    
  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server
    platform: linux/amd64   
  
  catalog.api:
    container_name: catalog.api
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  basket.api:
    container_name: basket.api
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      
  discount.grpc:
    container_name: discount.grpc
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    
volumes:
  postgres_catalog:
  postgres_basket: